Replace the 'US' and '$' symbols in the price
When the script gets the price and attempts to convert to float the following exception occurs:

Traceback (most recent call last):
  File "C:\Users\rpiston\Desktop\Proyectos\Python\Amazon-Warehouse-Scrapper-master\scrapper.py", line 49, in <module>
    print(round(float(soup.select('#olpLinkWidget_feature_div .a-color-base')
ValueError: could not convert string to float: '$368.9'